### ISSUE TITLE
Hello！I am very love your work, but I don't find your paper download link. Can you give me a link, thanks you!

### ISSUE THREAD

**Issue by Longtime1994** [nku-zhichengzhang/WECL#1]

**Comment by nku-zhichengzhang** [comment]
Hi, thank you for your interest~
The paper can be found in open access [CVPR](https://openaccess.thecvf.com/content/CVPR2023/papers/Zhang_Weakly_Supervised_Video_Emotion_Detection_and_Prediction_via_Cross-Modal_Temporal_CVPR_2023_paper.pdf) now.
