### ISSUE TITLE
pretrained-model

### ISSUE THREAD

**Issue by tungchey** [nku-zhichengzhang/WECL#2]
hello! I'm very interested in your work. Could you please share me the pretrained resnet101 model? Thank you.

**Comment by JinChow** [comment]
@tungchey Yeah, I am looking forward to getting the pretrained resnet101 model, I download one but I got errors during training,have you successfully receive the model?

**Comment by nku-zhichengzhang** [comment]
Thanks for your interest in our work.
Actually, the pre-trained model comes from [Can Spatiotemporal 3D CNNs Retrace the History of 2D CNNs and ImageNet?, CVPR18], which is publicly available. Now, the resnet_101_kinetics.pth file can be downloaded from their old released brunch (https://drive.google.com/drive/folders/1zvl89AgFAApbH0At-gMuZSeQB_LpNP-M).

**Comment by Learning-Deeply** [comment]
Yeah ,I have downloaded this pretrain model. But I always got errors when start training ,which are showed as follows.
![image](https://github.com/nku-zhichengzhang/WECL/assets/69828589/5a84f534-fb47-4234-b2ed-628c639798c2)
![image](https://github.com/nku-zhichengzhang/WECL/assets/69828589/1ed953c6-a9b8-4f2d-af39-573fd05b14b3)

**Comment by JinChow** [comment]
Hello, @nku-zhichengzhang First of all , I show my great appreciation for you and your contribution. When I run the WECL，my usage of gpu is really low,as you can see, I have change the n_thread and batch_size but it still trained slowly,I got the same issue when I run the VAANet, how can I solve it？
![image](https://github.com/nku-zhichengzhang/WECL/assets/69828589/0821abac-caee-42c4-9175-e7e48d80f096)

**Comment by nku-zhichengzhang** [comment]
@Learning-Deeply As you have only provided a very small amount of detail, we can only give you partial advice and may not be able to fully resolve your problem.
The point is that it's best to use our default settings. For example, a Linux-based system is required for environment support, and the default batch_size can help achieve original performance.
