### ISSUE TITLE
About dataset preprocessing, dataloader, and model

### ISSUE THREAD

**Issue by jhyukjang** [nku-zhichengzhang/WECL#3]
Hi! I'm very interested in your great work. I have some questions as below:

1. I have a problem like [here](https://github.com/maysonma/VAANet/issues/8). How to deal with these mp3 files?
2. Can you also provide a dataloader for ek6 and CAER datasets?
3. In contrast to VAANet, the current code in this git doesn't utilize audio input (model code). Where can I find complete code that uses both inputs, visual and audio?
Thx

**Comment by nku-zhichengzhang** [comment]
> Hi! I'm very interested in your great work. I have some questions as below:
> 
> 1. I have a problem like [here](https://github.com/maysonma/VAANet/issues/8). How to deal with these mp3 files?
> 2. Can you also provide a dataloader for ek6 and CAER datasets?
> 3. In contrast to VAANet, the current code in this git doesn't utilize audio input (model code). Where can I find complete code that uses both inputs, visual and audio?
>    Thx

Thanks for your questions.
1. We use zero to replace the missed audio features.
2. Actually, we use the same dataloader as the one for VE8.
3. It is a miss for reconstructing the whole structure of code. We will fix this soon.
