### ISSUE TITLE
Qustion about model of paper

### ISSUE THREAD

**Issue by Longtime1994** [nku-zhichengzhang/WECL#5]
def generate_visual_Erase_model(opt):
    model=VisualErase(
        snippet_duration=opt.snippet_duration,
        sample_size=opt.sample_size,
        n_classes=opt.n_classes,
        seq_len=opt.seq_len,
        pretrained_resnet101_path=opt.resnet101_pretrained,
    )
    model = nn.DataParallel(model)
    model=model.cuda()
    return model, model.parameters()

Hello, I have a question about this model, you input is video frames and audio in your papers, but this model input just video frames.  So I need your help of this question. If this is not the right model can you tell me the right one. Thanks.

**Comment by nku-zhichengzhang** [comment]
Thanks for indicating this point, this is the problem raised during code reconstruction, we will fix it in the next version.
