### ISSUE TITLE
Could you please provide the download link of "3d resnet101 model (.pth)"

### ISSUE THREAD

**Issue by YUO4YUM** [nku-zhichengzhang/WECL#6]
Thanks for your amazing repo
I want to run your code, but I don't know how to get the **"3d resnet101"** checkpoint.
Could you please provide the download link?

**Comment by nku-zhichengzhang** [comment]
The pre-trained model comes from [Can Spatiotemporal 3D CNNs Retrace the History of 2D CNNs and ImageNet?, CVPR18], which is publicly available. Now, the resnet_101_kinetics.pth file can be downloaded from their old released brunch (https://drive.google.com/drive/folders/1zvl89AgFAApbH0At-gMuZSeQB_LpNP-M).
