### ISSUE TITLE
Model Checkpoint

### ISSUE THREAD

**Issue by superoldzhang** [nku-zhichengzhang/WECL#7]
Thanks for your repo！Could you please provide your model checkpoint？

**Comment by JoJoistheBestOne** [comment]
+1

**Comment by nku-zhichengzhang** [comment]
Thx for your attention to our work. We have released ckpts [here](https://drive.google.com/drive/folders/1YYRkBlpaJRicUc5pWsbFlCETozISgnKy?usp=sharing).

**Comment by MuhammadHammadBashir** [comment]
Hi nku-zhichengzhang,  can you provide the inference code for the new videos?  
Or is there quick path that we can follow to achieve so,  since model ckpts released now.

**Comment by nku-zhichengzhang** [comment]
Check this [test.py](https://github.com/nku-zhichengzhang/CTEN/blob/main/test.py)
